kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2
    extraMounts:
        - containerPath: /var/lib/kubelet/config.json
          hostPath: ${HOME}/.docker/config.json
        - containerPath: /etc/containerd/certs.d
          hostPath: ${HOME}/.docker/certs.d
containerdConfigPatches:
  - |-
    version = 2

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"