namespace: sigstore

resources:
  - namespace.yaml
  - redis.yaml
  - trillian.yaml
  - rekor.yaml
  - fulcio.yaml
  - ctlog.yaml

patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: not-used
      spec:
        sourceRef:
          kind: OCIRepository
          name: code
          namespace: flux-system
        targetNamespace: sigstore
        interval: 1m
        retryInterval: 1m
        timeout: 1m
        prune: true
    target:
      kind: Kustomization
