---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trillian-pipeline
spec:
  dependsOn:
    - name: pipeline
      namespace: tekton
    - name: triggers
      namespace: tekton
  path: ./kubernetes/sigstore/trillian-pipeline
  timeout: 1m