---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trillian-database
spec:
  dependsOn:
    - name: cloudnativepg
      namespace: postgresql
  path: ./kubernetes/sigstore/trillian-database
  timeout: 1m
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: trilllian
      namespace: sigstore