---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
spec:
  dependsOn:
    - name: reflector
      namespace: reflector
  path: ./kubernetes/postgresql/postgresql
  timeout: 1m