kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: knative-release
spec:
  params:
    - name: version
      type: string
      description: Release tag of knative
      default: knative-v1.16.3
  workspaces:
    - name: shared
  tasks:
    - name: gather-assets
      taskSpec:
        params:
          - name: version
            type: string
        steps:
          - image:
      workspaces:
        - name: output
          workspace: shared
      params:
        - name: version
          value: $(params.version)
    - name: hack
      taskSpec:
        steps:
          - name: fix-dockerfile-from
            image: busybox
            script: |-
              cd $(workspaces.shared.path)/examples/deployment/docker
              sed -i 's/FROM golang/FROM docker.io\/golang/' log_server/Dockerfile
              cat log_server/Dockerfile
              sed -i 's/FROM golang/FROM docker.io\/golang/' log_signer/Dockerfile
              cat log_signer/Dockerfile
        workspaces:
          - name: shared
      runAfter: [clone]
    - name: build
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/daper/catalog
          - name: pathInRepo
            value: task/buildah/0.9/buildah.yaml
      runAfter: [clone, hack]
      workspaces:
        - name: source
          workspace: shared
      params:
        - name: CONTEXT
          value: $(workspaces.source.path)
        - name: PUSH_EXTRA_ARGS
          value: --tls-verify=false
      matrix:
        include:
          - name: log_server
            params:
              - name: DOCKERFILE
                value: $(workspaces.source.path)/examples/deployment/docker/log_server/Dockerfile
              - name: IMAGE
                value: kind-registry:5000/trillian-log-server:latest
          - name: log_signer
            params:
              - name: DOCKERFILE
                value: $(workspaces.source.path)/examples/deployment/docker/log_signer/Dockerfile
              - name: IMAGE
                value: kind-registry:5000/trillian-log-signer:latest
