apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: 16.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    serviceBindings:
      enabled: true
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: add
                path: /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflection-allowed
                value: "true"
              - op: add
                path: /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflection-auto-enabled
                value: "true"
              - op: add
                path: /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflection-auto-namespaces
                value: "sigstore"
            target:
              kind: Secret
              name: .*-svcbind-.*
