resources:
  - auth.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: init-trillian
    options:
      disableNameSuffixHash: true
    files:
      - storage.sql=https://raw.githubusercontent.com/google/trillian/refs/heads/master/storage/postgresql/schema/storage.sql