apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: approver-policy
spec:
  dependsOn:
    - name: cert-manager
  interval: 1m
  chart:
    spec:
      chart: cert-manager-approver-policy
      version: v0.17.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    crds:
      enabled: true