apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  dependsOn:
    - name: cert-manager
    - name: approver-policy
  interval: 1m
  chart:
    spec:
      chart: trust-manager
      version: v0.14.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    secretTargets:
      enabled: true
      authorizedSecretsAll: true
      authorizedSecrets: []
    app:
      webhook:
        tls:
          approverPolicy:
            enabled: true
            certManagerNamespace: cert-manager
