apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 1m
  timeout: 1m
  chart:
    spec:
      chart: redis
      version: 20.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  upgrade:
    force: true
  rollback:
    force: true
  values:
    architecture: standalone
    auth:
      enabled: false
    persistence:
      size: 1Gi