---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
spec:
  dependsOn:
    - name: pipeline
      namespace: tekton
    - name: triggers
      namespace: tekton
  path: ./kubernetes/knative/sources
