apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: 3.3.3
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values: {}
